### ISSUE TITLE
How to draw the t-SNE scatter plot? 

### ISSUE THREAD

**Issue by kmj0825** [vimar-gu/MinimaxDiffusion#1]
I'm a student studying this code. 
and now I'm reproducing the t-SNE scatter plot to see the diversity of this fine-tuned model.
but I don't have experience about reproducing the t-SNE scatter plot like this. 
so I can't draw the t-SNE scatter plot like fig.3 ..
could you please share the code to draw a t-SNE scatter plot like the one in fig.3 of the paper? 

Thank you very much!

**Comment by vimar-gu** [comment]
Thanks for your interest in our project. The t-SNE plot generally requries the following steps:
- Feature extraction
Here we extract features from multiple different datasets (the real one and several selected/generated ones). 
After feature extraction, concatenate these features for the subsequent dimension reduction. 
So we can have a set of features with the shape of [B1+B2+..., C], where B1, B2,... are the sample number of each datasets, and C is the channel number. Remember to transform the features into numpy arrays.
- T-SNE fit transform
Conduct the following code to get the transformed features with the shape of [B1+B2+..., 2]
```python
from sklearn.manifold import TSNE

tsne = TSNE()
tsne_features = tsne.fit_transform(features)
```
- Draw the figure
Run the following code to get the scatter figure
```python
import matplotlib.pyplot as plt

feature1, feature2, ... = np.split(tsne_features, [B1, B1+B2, ...]) # suppose you have more than 2 groups of features
fig = plt.figure(figsize=(...)) # set the figure size
ax1 = plt.subplot(...) # set the subplot e.g., plt.subplot(131)
ax1.scatter(feature1[:, 0], feature1[:, 1])
ax1.scatter(feature2[:, 0], feature2[:, 1])
# now you have a plot showing two groups of feature distibution
# the other subplots can be drawn in a similar manner
plt.tight_layout()
plt.savefig('tsne.png')
```

**Comment by kmj0825** [comment]
THANK YOU SO MUCH! 
 Thank you for showing me the method; I was able to draw the figures because of it. However, the figures look a bit different from Fig.3 in the paper, so I have a few more questions.
 
My process is as follows: Diffusion Train -> Diffusion Generation -> Train ResNet with training data -> Get feature of synthetic image with trained ResNet model -> draw t-SNE.

I wanted to extract features from the ResNet model, so I used the get_feature function in the resnet.py file. I extracted features from the layer just before the fc (fully connected) layer using data of size [100, 512] as the feature, but I am not sure if the method I used was correct.

1. Could I get a detailed description of feature extraction (like model, perplexity or else) ?

2. In Figure 3, the t-SNE plots are drawn differently for each model (DiT, Difffit, Minimax). I am curious if the images generated by each model (DiT, Difffit, Minimax) were also used in training the model (like ResNet, Convnet) from which the features were extracted. I used a ResNet checkpoint trained only with training images (not synthetic) to extract the features.

3. I used 1000 train and 100 synthetic samples, and I drew t-SNE differently for each class. Is this method correct?
![trained_data_n02086240_5](https://github.com/vimar-gu/MinimaxDiffusion/assets/67963713/d6be7d08-5a05-40ee-afa5-26d73f5ca6b7)

**Comment by vimar-gu** [comment]
Thanks for your follow-up questions!
1. My feature extraction process was generally the same as yours except that I directly used a pre-trained model. 
2. I used the pre-trained network so no training was conducted in my case. 
3. Regarding to the difference on the t-SNE plot, it is quite natural to get different results due to the randomness of the t-SNE fitting process. Even with the same features, you can get different plots in different runs. So if you cannot achieve the desired effects, perhaps give it more runs :)
