### ISSUE TITLE
Request for useful information about skip step diffusion

### ISSUE THREAD

**Issue by vvJesse** [vimar-gu/MinimaxDiffusion#2]
https://github.com/vimar-gu/MinimaxDiffusion/blob/969fc6f0a5e392d22fc2da39d8a130a4c55c6033/diffusion/respace.py#L67-L81

Hi I just find out here you mention skip step in diffusion model, which I am not familiar with. It seems that you do not use all time steps right? Would you please give me more explanation/reference papers about this method? Thank you.

**Comment by vimar-gu** [comment]
Thanks for your interest. The respacing  is used to accelerate the inference stage with fewer sampling steps. 
Then the scheduling parameter alpha also requires to be resampled according to the fewer steps. 
You can refer to [Improved Denoising Diffusion Probabilistic Models](https://arxiv.org/abs/2102.09672) and [Denoising Diffusion Implicit Models](https://arxiv.org/abs/2010.02502) for more details on the acceleration.
