### ISSUE TITLE
SRe2L performed poorly on the Imagewoof dataset

### ISSUE THREAD

**Issue by MikanYosoro** [vimar-gu/MinimaxDiffusion#7]
Hello, thank you for your contribution. I noticed that you cited the results of SRe2L on the full ImageNet-1K dataset. I extracted 10 classes of SRe2L which matched the Imagewoof dataset and attempted to verify the accuracy. However, the accuracy of SRe2L consistently hovered around 15%, and I am not sure if this is a normal phenomenon. I've attached a chart of my results and a piece of running code below, and I hope it is helpful to you.
`python train.py -d imagenet --imagenet_dir SRe2L original     -n resnet --nclass 10 --norm_type instance --ipc 100 --tag test --slct_type random --spec woof`
![curve_0](https://github.com/user-attachments/assets/b595497b-6e81-4a8b-a603-b6af2a46cd33)

**Comment by vimar-gu** [comment]
Thanks for the question. I think the main reason is that the images extracted by SRe2L are still chaotic and cannot provide sufficient information for fine-grained classification tasks. So the performance is bad on Imagewoof. When it comes to the whole ImageNet-1K, the phenomenom is mitigated.
